repos:
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v1.1.0
  hooks:
  - id: check-model-has-description
    args: [--manifest, "advertising/dbt/target/manifest.json"]
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.1.1
  hooks:
  - id: sqlfluff-lint
    # additional_dependencies: ['dbt-bigquery==1.5.0', 'sqlfluff-templater-dbt==2.1.1']
  - id: sqlfluff-fix
  # additional_dependencies: ['dbt-bigquery==1.5.0', 'sqlfluff-templater-dbt==2.1.1']
