site_name: KCL
site_url: https://www.kcl10.com
repo_url: https://github.com/kuanchoulai10/monorepo
repo_name: GitHub
edit_uri: edit/main/docs/
nav:
  - Home:
    - index.md
    - tags.md
  - About: about.md
  - Learning Plan:
    - learning-plan/index.md
    - learning-plan/2023.md
    - learning-plan/2024.md
  - Blog: 
    - blog/index.md

theme:
  name: material
  palette:
    primary: brown
    accent: amber
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - header.autohide
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - toc.follow

plugins:
  - monorepo
  - social
  - glightbox
  - tags:
      tags_file: tags.md
  - search:
      lang:
        - en
        - zh
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: medium
      post_excerpt: required
      post_url_format: "{file}"
      categories_allowed:
        - GCP
      draft_if_future_date: true
  - git-revision-date-localized:
      type: timeago
      timezone: Asia/Taipei
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: kuanchoulai10/monorepo
      branch: main

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - abbr
  - neoteroi.timeline
  - toc:
      permalink: true
      title: On This Page
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.snippets:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true

extra_css:
  - stylesheets/neoteroi-mkdocs-v1.0.4.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kuanchoulai/
    - icon: fontawesome/brands/github
      link: https://github.com/kuanchoulai10
    - icon: fontawesome/solid/paper-plane
      link: mailto:service@kcl10.com