site_name: KC's Data & Life Notes
site_description: Work experience, blog posts, and reflections on data science, AI, books, and finance — by KC, a data engineer exploring tech and life.
site_author: KC Lai
site_url: https://kcl10.com
repo_url: https://github.com/kuanchoulai10/monorepo
repo_name: GitHub
edit_uri: edit/main/docs/
nav:
  - Home:
    - index.md
  - About Me:
    - about-me/index.md
    - Work Experience:
      - about-me/work-experience/ust.md
      - about-me/work-experience/tvbs.md
      - about-me/work-experience/ninox.md
    - Education:
      - about-me/education/iii.md
      - about-me/education/nccu.md
      - about-me/education/ccu.md
    - Public Speakings:
      - about-me/public-speakings/index.md
  - Side Projects:
    - side-projects/index.md
    - side-projects/cross-cloud-unified-sql-data-pipelines.md
    - side-projects/sql-based-rag-application.md
  - Learning Plan:
    - learning-plan/index.md
    - learning-plan/2025.md
  - Blog: 
    - blog/index.md
    - tags.md

theme:
  name: material
  favicon: images/avatar.png
  logo: images/avatar.png
  font:
    text: Noto Serif TC
    code: Noto Sans Mono
  palette:
    primary: brown
    accent: amber
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - header.autohide
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - toc.follow

plugins:
  - monorepo
  - social
  - glightbox
  - drawio-exporter
  - tags:
      tags_file: tags.md
  - search:
      lang:
        - en
        - zh
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: medium
      post_excerpt: required
      post_url_format: "{file}"
      categories_allowed:
        - GCP
        - Google Analytics
        - mkdocs
        - python
      draft_if_future_date: true
  - git-revision-date-localized:
      type: timeago
      timezone: Asia/Taipei
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: kuanchoulai10/monorepo
      branch: main

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - abbr
  - tables
  - neoteroi.timeline
  - toc:
      permalink: true
      title: On This Page
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true

extra_css:
  - stylesheets/neoteroi-mkdocs-v1.0.4.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kuanchoulai/
    - icon: fontawesome/brands/github
      link: https://github.com/kuanchoulai10
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact-me@kcl10.com
  analytics:
    provider: google
    property: !ENV GA4_MEASUREMENT_ID
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!