site_name: KC's Data & Life Notes
site_description: A blog at the crossroads of data engineering, machine learning, AI, cloud architecture — with reflections on growth.
site_author: KC Lai
site_url: https://kcl10.com
repo_url: https://github.com/kuanchoulai10/monorepo
edit_uri: edit/main/docs/
nav:
  - Home:
    - index.md
  - About Me:
    - about-me/index.md
    - Work Experience:
      - about-me/work-experience/index.md
    - Public Speakings:
      - about-me/public-speakings/index.md
  - Side Projects:
    - side-projects/index.md
    - Fraud Detection (Data2ML Ops): "!include ./data2ml-ops/mkdocs.yml"
    - Retail Lakehouse: "!include ./retail-lakehouse/mkdocs.yml"
    - Unified SQL-based Data Pipelines: "!include ./data-mesh/mkdocs.yml"
    - arXiv Analytics Platform: "!include ./arxiv-analytics-platform/mkdocs.yml"
    - Trending Content Prediction: "!include ./dcard-hw/mkdocs.yml"
    # - side-projects/sql-based-rag-application.md
  - Learning Notes:
    - tech-notes/index.md
    - Spark:
      - tech-notes/spark/how-spark-works.md
      - tech-notes/spark/performance-tuning.md
      - Learning Spark (2020):
        - tech-notes/spark/learning-spark/ch1-2-intro-to-spark.md
        - tech-notes/spark/learning-spark/ch3-structured-apis.md
        - tech-notes/spark/learning-spark/ch7-tuning.md
    - Iceberg:
      - tech-notes/iceberg/iceberg-best-practices-in-aws.md
      - The Definitive Guide (2020):
        - tech-notes/iceberg/definitive-guide/ch4-tuning.md
      - tech-notes/kafka/iceberg-kafka-sink-connector.md
      - tech-notes/iceberg/migration.md
      - tech-notes/iceberg/disaster-recovery.md
      - tech-notes/iceberg/resources.md
      - tech-notes/iceberg/iceberg-in-prod-netflix-2023.md
    - Kafka:
      - tech-notes/kafka/exactly-once.md
      - tech-notes/kafka/iceberg-kafka-sink-connector.md
    - Flink:
      - tech-notes/flink/how-flink-works.md
    - Airflow:
      - tech-notes/airflow/how-airflow-works.md
    - Polaris:
      - tech-notes/polaris/policy.md
      - tech-notes/polaris/resources.md
    - DDIA:
      - tech-notes/ddia/ch8-transactions.md
    - Hive:
      - tech-notes/hive/architecture.md
    - SQLMesh:
      - tech-notes/sqlmesh/sqlmesh-vs-dbt-core.md
    - dbt:
      - tech-notes/dbt/index.md
    - Streaming Processing:
      - tech-notes/streaming-processing-window-types.md
    - RisingWave:
      - tech-notes/risingwave/index.md
    - Treasure Data:
      - tech-notes/treasure-data/index.md
    - LeetCode: "!include ./leetcode/mkdocs.yml"
    - Restful APIs with Flask: "!include ./restful-apis-with-flask/mkdocs.yml"
  - Blog: 
    - blog/index.md
  - Tags: tags.md
  - Recaps:
    - recaps/index.md
    - recaps/202508.md
    - recaps/202507.md
    - recaps/202506.md
    - recaps/202505.md
not_in_nav: |
  interview/

theme:
  name: material
  favicon: assets/avatar.png
  logo: assets/avatar.png
  font:
    text: IBM Plex Serif
    code: IBM Plex Mono
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  custom_dir: docs/assets/overrides
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - header.autohide
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - toc.follow
    - navigation.footer
    - header.autohide
    - announce.dismiss

plugins:
  - monorepo
  - social
  - glightbox
  - drawio-exporter
  - slides
  - meta:
      meta_file: .meta.yml
  - mkdocs-jupyter:
      include: ["*.ipynb"]
  - tags
  - search:
      lang:
        - en
        - zh
  - blog:
      blog_dir: blog
      blog_toc: true
      post_dir: "{blog}/posts"      
      post_url_format: "{file}"
      post_date_format: medium
      post_excerpt: required
      draft_if_future_date: true
      categories_allowed:
        - GCP
        - AWS
        - Azure
        - Data
        - AI
        - CI/CD
        - K8S
        - Books
        - Finance
        - Tech
        - Life
        - Google Analytics
        - MkDocs
        - Python
        - SEO
        - Raycast
  - git-committers:
      enabled: !ENV [MKDOCS_GIT_COMMITTERS, false]
      repository: kuanchoulai10/monorepo
      branch: main

markdown_extensions:
  - def_list
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - abbr
  - tables
  - neoteroi.timeline
  - toc:
      permalink: true
      title: On This Page
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      url_download: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/javascripts/katex.js
  - assets/javascripts/open-in-new-tabs.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


extra_css:
  - assets/stylesheets/neoteroi-mkdocs-v1.0.4.css
  - assets/stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kuanchoulai/
    - icon: fontawesome/brands/github
      link: https://github.com/kuanchoulai10
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact-me@kcl10.com
  analytics:
    provider: google
    property: !ENV GA4_MEASUREMENT_ID
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
