site_name: KC's Data & Life Notes
site_description: A blog at the crossroads of data engineering, machine learning, AI, cloud architecture — with reflections on growth.
site_author: KC Lai
site_url: https://kcl10.com
repo_url: https://github.com/kuanchoulai10/monorepo
edit_uri: edit/main/docs/
nav:
  - Home:
    - index.md
  - Side Projects:
    - side-projects/index.md
    - Data2ML Ops: "!include ./data2ml-ops/mkdocs.yml"
    - Trending Content Prediction: "!include ./dcard-hw/mkdocs.yml"
    - LeetCode: "!include ./leetcode/mkdocs.yml"
    # - side-projects/cross-cloud-unified-sql-data-pipelines.md
    - side-projects/sql-based-rag-application.md
    # - Data Mesh: "!include ./data-mesh/mkdocs.yml"
    - Restful APIs with Flask: "!include ./restful-apis-with-flask/mkdocs.yml"
  - Learning in Progress:
    - learning-in-progress/index.md
    - learning-in-progress/202506.md
    - learning-in-progress/202505.md
  - Blog: 
    - blog/index.md
  - Tags: tags.md
  - About Me:
    - about-me/index.md
    - Work Experience:
      - about-me/work-experience/ust/ust.md
      - about-me/work-experience/tvbs/tvbs.md
      - about-me/work-experience/ninox/ninox.md
      - about-me/work-experience/itri/itri.md
    - Public Speakings:
      - about-me/public-speakings/index.md

not_in_nav: |
  interview/

theme:
  name: material
  favicon: images/avatar.png
  logo: images/avatar.png
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    primary: white
    accent: indigo
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - header.autohide
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - toc.follow
    - navigation.footer
    - header.autohide
    - announce.dismiss

plugins:
  - monorepo
  - social
  - glightbox
  - drawio-exporter
  - slides
  - meta:
      meta_file: .meta.yml
  - mkdocs-jupyter:
      include: ["*.ipynb"]
  - tags
  - search:
      lang:
        - en
        - zh
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: medium
      post_excerpt: required
      post_url_format: "{file}"
      draft_if_future_date: true
      categories_allowed:
        - GCP
        - AWS
        - Azure
        - Data
        - AI
        - CI/CD
        - K8S
        - Books
        - Finance
        - Tech
        - Life
        - Google Analytics
        - MkDocs
        - Python
        - SEO
        - Raycast
  - git-committers:
      enabled: !ENV [MKDOCS_GIT_COMMITTERS, false]
      repository: kuanchoulai10/monorepo
      branch: main

markdown_extensions:
  - def_list
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - abbr
  - tables
  - neoteroi.timeline
  - toc:
      permalink: true
      title: On This Page
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      url_download: true
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - javascripts/open-in-new-tabs.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


extra_css:
  - stylesheets/neoteroi-mkdocs-v1.0.4.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kuanchoulai/
    - icon: fontawesome/brands/github
      link: https://github.com/kuanchoulai10
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact-me@kcl10.com
  analytics:
    provider: google
    property: !ENV GA4_MEASUREMENT_ID
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
