site_name: Monorepo
repo_url: https://github.com/kuanchoulai10/monorepo
repo_name: GitHub
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - About: about.md
  - Blog: 'blog/index.md'

theme:
  name: material
  palette:
    primary: brown
    accent: amber
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - header.autohide
    - content.action.edit
    - content.code.copy
    - content.tabs.link
plugins:
  - monorepo
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Asia/Taipei
      locale: zh
      enable_creation_date: true
      fallback_to_build_date: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.details
  # - pymdownx.superfences:
  # - pymdownx.snippets:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
