site_name: Monorepo
repo_url: https://github.com/kuanchoulai10/monorepo
repo_name: GitHub
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  palette:
    primary: brown
    accent: amber
  language: zh-TW
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - header.autohide
    - content.action.edit
    - content.code.copy
    - content.tabs.link
plugins:
  - monorepo
  - search
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Asia/Taipei
      locale: zh
      enable_creation_date: true
      fallback_to_build_date: true
markdown_extensions:
  - admonition
