version: '3'

output:
  group:
    begin: "::group::{{.TASK}}"
    end: "::endgroup::"

tasks:
  serve-docs:
    desc: Serve the MkDocs site locally with live reload
    env:
      JUPYTER_PLATFORM_DIRS: "1"
    cmds:
      - uv run mkdocs serve
